### PR TITLE
add jsx-curly-brace-presence rule

### PR DESCRIPTION
**Pull request by TomPridham**
## Change Type

* [x] Feature
* [ ] Chore
* [ ] Bug Fix

## Change Level

* [ ] major
* [ ] minor
* [x] patch

### CODE REVIEW

**Comment by zacanger** [comment]
That 0 doesn't do what you think it does.

**Comment by TomPridham** [comment]
see, this is why these numbers are straight trash

**Comment by zacanger** [comment]
They're really not, strings are worse. Is it `warning` or `warn`? I have no idea.

**Comment by TomPridham** [comment]
you would have the other rules to look at, tho. even with other rules i have no idea what `0` means

**Pull request merged**
